
apiVersion: v1
kind: ConfigMap
metadata:
  name: fandable-staging-configmap
  namespace: fandable-staging
data:
  # https://stackoverflow.com/questions/49129809/kubernetes-how-to-send-data-from-a-pod-to-another-pod-in-kubernetes
  react-app-server-base: http://fandable-staging-backend-service.fandable-staging
  react-app-server-port: "8080"
  mongo-initdb-database: task-management
  mongo-port-for-backend: "27017"
  mongo-host-for-backend: fandable-staging-mongo-service.fandable-staging

